image: ubuntu:trusty

variables:
  GITHUB_PAGE: 'https://feryardiant:$GH_DEPLOY_TOKEN@github.com/feryardiant/static-spa.git'

pages:
  artifacts:
    paths:
      - public
  environment:
    name: gitlab-static
    url: https://feryardiant.gitlab.io/static-spa
  before_script:
    - apt-get update && apt-get install git openssh
    - git config user.name $GITLAB_USER_NAME
    - git config user.email $GITLAB_USER_EMAIL
  script:
    - git subtree push -P public -b master $GITHUB_PAGE gh-pages
    - echo 'OK'
  only:
    - master
