image: gitlab/gitlab-runner:alpine

stages:
  - deploy

variables:
  NAMESPACE: $CI_PROJECT_NAMESPACE
  PROJECT: $CI_PROJECT_NAME
  GITHUB_PAGE: 'https://$NAMESPACE:$DEPLOY_TOKEN@github.com/$NAMESPACE/$PROJECT.git'

environment:
  name: gitlab-static
  url: https://feryardiant.gitlab.io/static-spa

pages:
  stage: deploy
  artifacts:
    paths:
      - public
  before_script:
    - /bin/sh -c "apk update && apk add --no-cache bash git openssh"
    - git config user.name $GITLAB_USER_NAME
    - git config user.email $GITLAB_USER_EMAIL
  script:
    - git subtree push -P public -b master $GITHUB_PAGE gh-pages
    - echo 'OK'
  only:
    - master
