image: gitlab/gitlab-runner:alpine

stages:
  - deploy

variables:
  GITHUB_PAGE: 'https://feryardiant:$GH_DEPLOY_TOKEN@github.com/feryardiant/static-spa.git'


pages:
  stage: deploy
  artifacts:
    paths:
      - public
  environment:
    name: gitlab-static
    url: https://feryardiant.gitlab.io/static-spa
  before_script:
    - /bin/sh -c "apk update && apk add --no-cache bash git openssh"
    - git config user.name $GITLAB_USER_NAME
    - git config user.email $GITLAB_USER_EMAIL
  script:
    - git subtree push -P public -b master $GITHUB_PAGE gh-pages
    - echo 'OK'
  only:
    - master
