image: node:10.15

stages:
  - deploy

pages:
  stage: deploy
  artifacts:
    paths:
      - public
  environment:
    name: gitlab-static
    url: https://feryardiant.gitlab.io/static-spa
  script:
    - echo 'OK'
  only:
    - master
