image: gitlab/gitlab-runner:alpine

stages:
  - deploy

pages:
  stage: deploy
  artifacts:
    paths:
      - public
  environment:
    name: gitlab-static
    url: https://feryardiant.gitlab.io/static-spa
  variables:
    GITHUB_PAGE: 'https://$CI_PROJECT_NAMESPACE:$DEPLOY_TOKEN@github.com/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME.git'
  before_script:
    - apk add git
    - git config user.name $GITLAB_USER_NAME
    - git config user.email $GITLAB_USER_EMAIL
  script:
    - git subtree push -P public -b master $GITHUB_PAGE gh-pages
    - echo 'OK'
  only:
    - master
